# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/mainui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 397)
        MainWindow.setMinimumSize(QtCore.QSize(451, 397))
        MainWindow.setMaximumSize(QtCore.QSize(451, 397))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.roundClear = QtWidgets.QPushButton(self.centralwidget)
        self.roundClear.setGeometry(QtCore.QRect(240, 330, 111, 28))
        self.roundClear.setObjectName("roundClear")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.redRound = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.redRound.setAlignment(QtCore.Qt.AlignCenter)
        self.redRound.setObjectName("redRound")
        self.verticalLayout.addWidget(self.redRound)
        self.radScore = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.radScore.setDigitCount(2)
        self.radScore.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.radScore.setProperty("intValue", 0)
        self.radScore.setObjectName("radScore")
        self.verticalLayout.addWidget(self.radScore)
        self.redAddRound = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.redAddRound.setObjectName("redAddRound")
        self.verticalLayout.addWidget(self.redAddRound)
        self.redAdd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.redAdd.setObjectName("redAdd")
        self.verticalLayout.addWidget(self.redAdd)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(280, 20, 160, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.blueRound = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.blueRound.setAlignment(QtCore.Qt.AlignCenter)
        self.blueRound.setObjectName("blueRound")
        self.verticalLayout_2.addWidget(self.blueRound)
        self.blueScore = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.blueScore.setDigitCount(2)
        self.blueScore.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.blueScore.setProperty("intValue", 0)
        self.blueScore.setObjectName("blueScore")
        self.verticalLayout_2.addWidget(self.blueScore)
        self.blueAddRound = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.blueAddRound.setObjectName("blueAddRound")
        self.verticalLayout_2.addWidget(self.blueAddRound)
        self.blueAdd = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.blueAdd.setObjectName("blueAdd")
        self.verticalLayout_2.addWidget(self.blueAdd)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.roundSet = QtWidgets.QTextEdit(self.centralwidget)
        self.roundSet.setGeometry(QtCore.QRect(170, 290, 111, 29))
        self.roundSet.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.roundSet.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.roundSet.setObjectName("roundSet")
        self.author = QtWidgets.QLabel(self.centralwidget)
        self.author.setGeometry(QtCore.QRect(350, 370, 91, 20))
        self.author.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.author.setObjectName("author")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 344, 41, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../img/favicon.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.scoreClear = QtWidgets.QPushButton(self.centralwidget)
        self.scoreClear.setGeometry(QtCore.QRect(110, 330, 111, 28))
        self.scoreClear.setObjectName("scoreClear")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "北科電競社轉播用記分板 v2.1"))
        self.roundClear.setText(_translate("MainWindow", "大分清除"))
        self.label.setText(_translate("MainWindow", "紅隊分數"))
        self.redRound.setText(_translate("MainWindow", "○○"))
        self.redAddRound.setText(_translate("MainWindow", "紅隊大分"))
        self.redAdd.setText(_translate("MainWindow", "紅隊加分"))
        self.label_2.setText(_translate("MainWindow", "藍隊分數"))
        self.blueRound.setText(_translate("MainWindow", "○○"))
        self.blueAddRound.setText(_translate("MainWindow", "藍隊大分"))
        self.blueAdd.setText(_translate("MainWindow", "藍隊加分"))
        self.roundSet.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p></body></html>"))
        self.roundSet.setPlaceholderText(_translate("MainWindow", "大分"))
        self.author.setText(_translate("MainWindow", "auth by RuiCat"))
        self.scoreClear.setText(_translate("MainWindow", "小分歸零"))
